apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 80       # Внутренний порт сервиса
      targetPort: 80 # Порт контейнера
      nodePort: 30080 # Порт на нодах (30000-32767)
